### ISSUE TITLE
Migrate testing to use `rules_bazel_integration_test`

### ISSUE THREAD

**Issue by adierkens** [player-ui/rules_player#54]
Right now the tests only run via a custom script. Migrate to use https://github.com/bazel-contrib/rules_bazel_integration_test so they execute via the normal `bazel test` mechanism

**Comment by intuit-svc** [comment]
:rocket: Issue was released in [`v1.1.0`](https://github.com/player-ui/rules_player/releases/tag/v1.1.0) :rocket:
