### ISSUE TITLE
`create_package_json` resolves incorrect dependencies

### ISSUE THREAD

**Issue by adierkens** [player-ui/rules_player#7]
When dependencies are declared in a rule, when they get resolved into a package json, they get resolved into the flattened first package in tree

This is prevalent in the [@player-ui/player](https://github.com/player-ui/player/blob/main/core/player/BUILD#L6) package where the first dependency added is for `binding-grammar` instead of `binding`

**Comment by intuit-svc** [comment]
:rocket: Issue was released in [`v0.2.1`](https://github.com/player-ui/rules_player/releases/tag/v0.2.1) :rocket:
